### ISSUE TITLE
Removing a transition and adding it again raises KeyError

### ISSUE THREAD

**Issue by Synss** [pytransitions/transitions#253]
I believe that I found a bug with `remove_transition` #162. I do not think that I am able to fix it but here is how to reproduce it:
```python
from transitions import Machine

machine = Machine()

machine.add_states(["A", "B", "C"])
machine.add_transition("next_state", "A", "B")
machine.add_transition("next_state", "B", "C")     # same trigger, other transition

machine.remove_transition("next_state", "A", "B")  # should only remove the first transition
machine.add_transition("next_state", "A", "C")     # raises KeyError: 'A'
```

Here is a copy of the full traceback:
```python
Traceback (most recent call last):
  File "toto.py", line 10, in <module>
    machine.add_transition("next_state", "A", "C")
  File "/home/laurin/src/transitions.git/transitions/core.py", line 701, in ad
d_transition
    self.events[trigger].add_transition(t)
  File "/home/laurin/src/transitions.git/transitions/core.py", line 284, in ad
d_transition
    self.transitions[transition.source].append(transition)
KeyError: 'A'
```

I have added a test in your `test_core.py` that also reproduces the bug, here is the diffs:
```patch
diff --git a/tests/test_core.py b/tests/test_core.py
index 33e0bd8..9596521 100644
--- a/tests/test_core.py
+++ b/tests/test_core.py
@@ -879,6 +879,14 @@ class TestTransitions(TestCase):
         self.stuff.machine.remove_transition('go', dest='D')
         self.assertFalse(hasattr(self.stuff, 'go'))
 
+    def test_remove_and_add_transition(self):
+        self.stuff.machine.add_transition('go', 'A', 'B')
+        self.stuff.machine.add_transition('go', 'B', 'C')
+        self.stuff.machine.remove_transition('go', 'A', 'B')
+        self.stuff.machine.add_transition('go', 'A', 'B')
+        self.stuff.go()
+        self.assertEqual(self.stuff.state, 'B')
+
     def test_reflexive_transition(self):
         self.stuff.machine.add_transition('reflex', ['A', 'B'], '=', after='increase_level')
         self.assertEqual(self.stuff.state, 'A')
```

Do not hesitate to ask me if you need anything else and thank you for your time!

**Comment by aleneum** [comment]
Hi @Synss,

good catch! During `remove_transitions`, the `defaultdict` of `Event.transitions` had been falsely converted into a normal `dict`. Thanks for the test and the report. I integrated it into the existing ` test_remove_transition`. Should be fixed now.

**Comment by Synss** [comment]
You are really fast, thank you! I'll try it tomorrow.

**Comment by Synss** [comment]
You fix works perfectly!
