### ISSUE TITLE
Nested State Separator, UTF-8, and GraphViz

### ISSUE THREAD

**Issue by Shaun-Griffith-Hive** [pytransitions/transitions#295]
UTF-8 nested state separator is not handled by GraphViz.

This isn't really a problem with pytransitions, but with graphviz. Using the nested example in readme, modified for graphing:

```
from transitions.extensions import HierarchicalGraphMachine as Machine
from transitions.extensions.nesting import NestedState
NestedState.separator = '↦'
states = ['A', 'B',
  {'name': 'C', 'children':['1', '2',
    {'name': '3', 'children': ['a', 'b', 'c']}
  ]}
]

transitions = [
    ['reset', 'C', 'A'],
    ['reset', 'C↦2', 'C']  # overwriting parent reset
]

# we rely on auto transitions
machine = Machine(states=states, transitions=transitions, initial='A')
machine.get_graph().draw('Nesting_FSM.png', prog='dot')
```

...gives this error:
```
Traceback (most recent call last):
  File "./nesting_example.py", line 18, in <module>
    machine.get_graph().draw('Nesting_FSM.png', prog='dot')
  File "/home/shaun/.virtualenvs/py36/lib/python3.6/site-packages/pygraphviz/agraph.py", line 1474, in draw
    data = self._run_prog(prog, args)
  File "/home/shaun/.virtualenvs/py36/lib/python3.6/site-packages/pygraphviz/agraph.py", line 1338, in _run_prog
    warnings.warn(b"".join(errors), RuntimeWarning)
TypeError: cannot use a string pattern on a bytes-like object
```
Changing the `'↦'` to, e.g., `'=>'`, fixes the problem.

(Please do what you will with this issue. I couldn't find an existing open or closed issue, and it would have helped me here. I'm off to see if I can find/report it for graphviz.)

**Comment by Shaun-Griffith-Hive** [comment]
Sorry, my version of pygraphviz was out of date. After pulling down the pygraphviz source, there was no problem.
