### ISSUE TITLE
AttributeError: 'indicate_logged_in' does not exist on <Machine@82249904>

### ISSUE THREAD

**Issue by Edvard-D** [pytransitions/transitions#335]
I've run into an error that I've been trying to make sense of. For context, I have the following base class that derives from Machine and implements the state machine, initialized as follows:

`

    def __init__(self, label: str):
        self.label = label
        states = [
            'logged_in',
            'logged_out'
        ]
        super(Base, self).__init__(states=states, initial='logged_out')
        self.add_transition('log_in', 'logged_out', 'logged_in')
        self.add_transition('log_out', 'logged_in', 'logged_out')`

This class has a method that uses asyncio and arsenic (async webdriver) to have the user authenticate themselves.

`

    async def authenticate(self):
        async with visible.get_session() as session:
            await session.get(self.login_url)
            while self.state == 'logged_out':
                try:
                    await session.get_element(self.element_selector)
                    self.cookies = session.get_all_cookies()
                    self.log_in()
                except arsenic.errors.NoSuchElement:
                    await asyncio.sleep(1)`

You can see that I'm trying to transition the state using `self.log_in`, but I'm running into an error. Am I doing something wrong?

`Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python37-32\lib\site-packages\transitions\core.py", line 1018, in resolve_callable
    func = getattr(event_data.model, func)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python37-32\lib\site-packages\transitions\core.py", line 1108, in __getattr__
    raise AttributeError("'{}' does not exist on <Machine@{}>".format(name, id(self)))
AttributeError: 'indicate_logged_in' does not exist on <Machine@82249904>`

`During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python37-32\lib\site-packages\transitions\core.py", line 1021, in resolve_callable
    mod, name = func.rsplit('.', 1)
ValueError: not enough values to unpack (expected 2, got 1)`

`During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "c:\Users\HP\.vscode\extensions\ms-python.python-2019.1.0\pythonFiles\ptvsd_launcher.py", line 45, in <module>
    main(ptvsdArgs)
  File "c:\Users\HP\.vscode\extensions\ms-python.python-2019.1.0\pythonFiles\lib\python\ptvsd\__main__.py", line 348, in main
    run()
  File "c:\Users\HP\.vscode\extensions\ms-python.python-2019.1.0\pythonFiles\lib\python\ptvsd\__main__.py", line 253, in run_file
    runpy.run_path(target, run_name='__main__')
  File "C:\Users\HP\AppData\Local\Programs\Python\Python37-32\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python37-32\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python37-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\HP\Desktop\Automator\setup.py", line 27, in <module>
    main()
  File "C:\Users\HP\Desktop\Automator\setup.py", line 23, in main
    loop.run_until_complete(kl24.authenticate())
  File "C:\Users\HP\AppData\Local\Programs\Python\Python37-32\lib\asyncio\base_events.py", line 568, in run_until_complete
    return future.result()
  File "C:\Users\HP\Desktop\Automator\automator\domains\kl24.py", line 20, in authenticate
    self.log_in()
  File "C:\Users\HP\AppData\Local\Programs\Python\Python37-32\lib\site-packages\transitions\core.py", line 383, in trigger
    return self.machine._process(func)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python37-32\lib\site-packages\transitions\core.py", line 1046, in _process
    return trigger()
  File "C:\Users\HP\AppData\Local\Programs\Python\Python37-32\lib\site-packages\transitions\core.py", line 399, in _trigger
    return self._process(event_data)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python37-32\lib\site-packages\transitions\core.py", line 409, in _process
    if trans.execute(event_data):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python37-32\lib\site-packages\transitions\core.py", line 263, in execute
    self._change_state(event_data)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python37-32\lib\site-packages\transitions\core.py", line 274, in _change_state
    event_data.machine.get_state(self.dest).enter(event_data)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python37-32\lib\site-packages\transitions\core.py", line 120, in enter
    event_data.machine.callback(handle, event_data)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python37-32\lib\site-packages\transitions\core.py", line 1001, in callback
    func = self.resolve_callable(func, event_data)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python37-32\lib\site-packages\transitions\core.py", line 1027, in resolve_callable
    raise AttributeError("Callable with name '%s' could neither be retrieved from the passed "
AttributeError: Callable with name '%s' could neither be retrieved from the passed model nor imported from a module.`

**Comment by potens1** [comment]
Hi,

Maybe I'm wrong (fast read), but, if you add `model=self` in the `super().__init__()`, it should correct it.
The error I see means the model is not your instance (but I can be wrong).

Hope it helps

**Comment by aleneum** [comment]
Hello @Edvard-D,

where is `indicate_logged_in` coming from. The error informs you that `indicate_logged_in` cannot be found as part of the model, in your case your `Machine` instance.

**Comment by Edvard-D** [comment]
@aleneum You're right, thanks. Realized that it's being registered in a different class but the callback function needs to be assigned to the model.
